"""adding unique constraint

Revision ID: 064c38c33acf
Revises: af5a92f6cdaf
Create Date: 2023-05-01 16:47:17.889918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "064c38c33acf"
down_revision = "af5a92f6cdaf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint("usersss", ["username"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("usersss", type_="unique")

    # ### end Alembic commands ###
